f1_analytics:
  outputs:
    dev:
      type: duckdb
      path: /Users/lucas/Documents/code/f1-analytics/f1_analytics/f1.duckdb
      threads: 4
      schema: dev

    prod:
      type: duckdb
      path: /Users/lucas/Documents/code/f1-analytics/f1_analytics/f1.duckdb
      threads: 4
      # schema: prod

  target: prod
